services:

  # Reverse proxy to front-end and backend requests to the appropriate ports
  # See nginx/nginx.conf for configuration details. Start at http://localhost:3000
  reverse-proxy:
    image: nginx:latest
    network_mode: "host"
    ports:
      - 3000:3000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - db
      - adminer

  # Use postgres/example as user/password credentials
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  # Run docker compose up, wait for it to initialize completely, and visit http://localhost:8080 or http://host-ip:8080 (as appropriate).
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080 # Maps port 8080 inside the container to port 8088 on the host machine so we can run webapps on port 8080

